# Use an official base image
FROM ubuntu:latest

# Install necessary packages
RUN apt update && apt install -y gcc

# Set the working directory in the container
WORKDIR /app

# Copy the C file to the container
COPY discovery.h processing.h constants.h client.h  /app/
COPY RunClient.c discovery.c processing.c client.c  /app/

# Compile the C program
RUN gcc RunClient.c -o RunClient discovery.c processing.c client.c -lpthread

# Use ENTRYPOINT to allow passing arguments
ENTRYPOINT ["./RunClient"]